### ISSUE TITLE
Unit test example?

### ISSUE THREAD

**Issue by james-powis** [lipanski/ansible-custom-modules-demo#1]
Would love to see an example unit test.

**Comment by lipanski** [comment]
@james-powis it's probably not hard to do unit tests but I'd usually prefer https://molecule.readthedocs.io/en/stable/ (more like integration testing). in any case, I haven't touched this repo in quite a while and probably won't touch any time soon. happy though that it still raises interest so thanks for your comment.

**Comment by ssbarnea** [comment]
I would be really interested to see an example on custom module tested with pytest. Molecule is super cool but is more of a functional testing, not replacing the need for unittest.
